/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import TextSlider from "./TextSlider";
import InfoSection1 from "./InfoSection1";
import InfoSection2 from "./InfoSection2";
import Footer from "./Footer";

export default function MyComponent(props) {
  return (
    <>
      <TextSlider />
      <InfoSection1 />
      <InfoSection2 />
    </>
  );
}
